# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imagename: 'pipeline-docker-image'

steps:
- task: Docker@2
  displayName: build a image
  inputs:
    repository: $(imageName) 
    command: build
    dockerfile: app/Dockerfile
